In [1]:
# --- [CELL 0]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 1}
import datetime as dt
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

import warnings
warnings.simplefilter(action="ignore")

pd.set_option('display.max_columns',1000)
pd.set_option('display.width', 500)
pd.set_option('display.float_format',lambda x : '%.2f' % x)

In [2]:
# --- [CELL 1]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 2}
df_ = pd.read_csv("data/dataset.csv", compression="gzip")
df = df_.copy()
df.head()

   RecipeId                                        Name  CookTime  PrepTime  TotalTime                              RecipeIngredientParts  Calories  FatContent  SaturatedFatContent  CholesterolContent  SodiumContent  CarbohydrateContent  FiberContent  SugarContent  ProteinContent                                 RecipeInstructions
0        38           Low-Fat Berry Blue Frozen Dessert      1440        45       1485  c("blueberries", "granulated sugar", "vanilla ...    170.90        2.50                 1.30                8.00          29.80                37.10          3.60         30.20            3.20  c("Toss 2 cups berries with sugar.", "Let stan...
1        41              Carina's Tofu-Vegetable Kebabs        20      1440       1460  c("extra firm tofu", "eggplant", "zucchini", "...    536.10       24.00                 3.80                0.00        1558.60                64.20         17.30         32.10           29.30  c("Drain the tofu, carefully squeezing out exc...
2        42                                Cabbage Soup        30        20         50  c("plain tomato juice", "cabbage", "onion", "c...    103.60        0.40                 0.10                0.00         959.30                25.10          4.80         17.70            4.30  c("Mix everything together and bring to a boil...
3        45  Buttermilk Pie With Gingersnap Crumb Crust        50        30         80  c("sugar", "margarine", "egg", "flour", "salt"...    228.00        7.10                 1.70               24.50         281.80                37.50          0.50         24.70            4.20  c("Preheat oven to 350°F.", "Make pie crust, u...
4        46                     A Jad - Cucumber Pickle         0        25         25                          c("rice vinegar", "haeo")      4.30        0.00                 0.00                0.00           0.70                 1.10          0.20          0.20            0.10  c("Slice the cucumber in four lengthwise, then...

In [3]:
# --- [CELL 2]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 3}
def grab_col_names(dataframe, cat_th=10, car_th=20):

    cat_cols = [col for col in dataframe.columns if dataframe[col].dtypes == "O"]
    num_but_cat = [col for col in dataframe.columns if dataframe[col].nunique() < cat_th and
                   dataframe[col].dtypes != "O"]
    cat_but_car = [col for col in dataframe.columns if dataframe[col].nunique() > car_th and
                   dataframe[col].dtypes == "O"]
    cat_cols = cat_cols + num_but_cat
    cat_cols = [col for col in cat_cols if col not in cat_but_car]

    # num_cols
    num_cols = [col for col in dataframe.columns if dataframe[col].dtypes != "O"]
    num_cols = [col for col in num_cols if col not in num_but_cat]

    print(f"Observations: {dataframe.shape[0]}")
    print(f"Variables: {dataframe.shape[1]}")
    print(f'cat_cols: {len(cat_cols)}')
    print(f'num_cols: {len(num_cols)}')
    print(f'cat_but_car: {len(cat_but_car)}')
    print(f'num_but_cat: {len(num_but_cat)}')
    return cat_cols, num_cols, cat_but_car

In [4]:
# --- [CELL 3]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 4}
cat_cols, num_cols, num_but_cat = grab_col_names(df)

Observations: 375703
Variables: 16
cat_cols: 0
num_cols: 13
cat_but_car: 3
num_but_cat: 0

In [5]:
# --- [CELL 4]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 5}
def outlier_thresholds(dataframe, col_name, q1=0.01, q3=0.99):
    quartile1= dataframe[col_name].quantile(q1)
    quartile3= dataframe[col_name].quantile(q3)
    interquantile_range = quartile3 -quartile1
    up_limit= quartile3 +1.5 * interquantile_range
    low_limit= quartile1 -1.5 * interquantile_range
    return low_limit, up_limit

In [6]:
# --- [CELL 5]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 6}
def replace_with_thresholds(dataframe, variable):
    low_limit, up_limit = outlier_thresholds(dataframe, variable)
    dataframe.loc[(dataframe[variable] < low_limit), variable] = low_limit
    dataframe.loc[(dataframe[variable] > up_limit), variable] = up_limit

for col in num_cols:
    replace_with_thresholds(df, col)

In [7]:
# --- [CELL 6]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 7}
def check_outlier(dataframe, col_name):
    low_limit, up_limit = outlier_thresholds(dataframe, col_name)
    if dataframe[(dataframe[col_name] > up_limit) | (dataframe[col_name] < low_limit)].any(axis=None):
        return True
    else:
        return False

check_outlier(df,num_cols)

False

In [8]:
# --- [CELL 7]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 8}
df= df.iloc[:,1:]

In [9]:
# --- [CELL 8]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 9}
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
from yellowbrick.cluster import KElbowVisualizer
from scipy.cluster.hierarchy import linkage
from scipy.cluster.hierarchy import dendrogram
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import AgglomerativeClustering

In [10]:
# --- [CELL 9]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 10}
cat_cols, num_cols, num_but_cat = grab_col_names(df)

Observations: 375703
Variables: 15
cat_cols: 0
num_cols: 12
cat_but_car: 3
num_but_cat: 0

In [11]:
# --- [CELL 10]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 11}
df2=df.copy()

In [12]:
# --- [CELL 11]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 12}
sc = MinMaxScaler((0, 1))
df2[num_cols] = sc.fit_transform(df2[num_cols])

In [13]:
# --- [CELL 12]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 13}
kmeans = KMeans(n_clusters=30, n_init="auto").fit(df2[["TotalTime","Calories","SugarContent"]])

In [14]:
# --- [CELL 13]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 14}
clusters_kmeans = kmeans.labels_
clusters_kmeans

array([14, 14, 15, ...,  9,  1, 29], dtype=int32)

In [15]:
# --- [CELL 14]: ---
# cell_state: unchanged
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 15}
df["kmeans_cluster"] = clusters_kmeans
df["kmeans_cluster"]= df["kmeans_cluster"] + 1
df.head()

                                         Name  CookTime  PrepTime  TotalTime                              RecipeIngredientParts  Calories  FatContent  SaturatedFatContent  CholesterolContent  SodiumContent  CarbohydrateContent  FiberContent  SugarContent  ProteinContent                                 RecipeInstructions  kmeans_cluster
0           Low-Fat Berry Blue Frozen Dessert      1200        45    1485.00  c("blueberries", "granulated sugar", "vanilla ...    170.90        2.50                 1.30                8.00          29.80                37.10          3.60         30.20            3.20  c("Toss 2 cups berries with sugar.", "Let stan...              15
1              Carina's Tofu-Vegetable Kebabs        20       600    1460.00  c("extra firm tofu", "eggplant", "zucchini", "...    536.10       24.00                 3.80                0.00        1558.60                64.20         17.30         32.10           29.30  c("Drain the tofu, carefully squeezing out exc...              15
2                                Cabbage Soup        30        20      50.00  c("plain tomato juice", "cabbage", "onion", "c...    103.60        0.40                 0.10                0.00         959.30                25.10          4.80         17.70            4.30  c("Mix everything together and bring to a boil...              16
3  Buttermilk Pie With Gingersnap Crumb Crust        50        30      80.00  c("sugar", "margarine", "egg", "flour", "salt"...    228.00        7.10                 1.70               24.50         281.80                37.50          0.50         24.70            4.20  c("Preheat oven to 350°F.", "Make pie crust, u...              10
4                     A Jad - Cucumber Pickle         0        25      25.00                          c("rice vinegar", "haeo")      4.30        0.00                 0.00                0.00           0.70                 1.10          0.20          0.20            0.10  c("Slice the cucumber in four lengthwise, then...              30

In [16]:
# --- [CELL 15]: ---
# cell_state: edited
# execution_status: {'status': 'ok', 'done': True, 'execution_count': 16}
# === BEFORE (original) ===
# df.groupby('kmeans_cluster').agg({1: ['count','mean', 'median', 'sum'],
#                                     2: ['count','mean', 'median', 'sum'],
#                                     3: ['count','mean', 'median', 'sum'],
#                                     4: ['count','mean','median', 'sum']})

# === AFTER (edited) ===
df.groupby('kmeans_cluster')[['TotalTime', 'Calories', 'SugarContent', 'ProteinContent']].agg(['count', 'mean', 'median', 'sum'])

               TotalTime                            Calories                          SugarContent                        ProteinContent
                   count    mean  median        sum    count   mean median        sum        count  mean median       sum          count  mean median       sum
kmeans_cluster
1                  37017   37.73   30.00 1396574.00    37017 200.34 198.40 7415906.40        37017  1.26   1.20  46616.90          37017 11.08   8.00 410021.80
2                  12306   46.76   35.00  575479.00    12306 228.70 232.10 2814332.30        12306 22.01  21.90 270861.70          12306  4.75   3.50  58427.10
3                  10976   58.84   45.00  645841.00    10976 563.93 552.55 6189643.70        10976  6.94   6.90  76164.00          10976 29.93  29.20 328504.30
4                  15555   41.76   30.00  649600.00    15555 161.88 162.50 2517985.70        15555 13.72  13.60 213343.60          15555  3.84   2.70  59685.50
5                   8418   64.17   50.00  540166.00     8418 366.95 366.20 3088959.70         8418 36.95  36.90 311037.70           8418  7.22   5.00  60773.30
6                    760 1569.45 1470.00 1192780.00      760 275.97 227.20  209737.80          760 14.12  13.60  10735.00            760 11.01   4.40   8371.20
7                  26431   44.46   35.00 1175226.00    26431 253.54 254.10 6701392.30        26431  4.34   4.30 114713.30          26431 13.23  10.70 349602.40
8                  19178   52.42   40.00 1005380.00    19178 411.51 409.40 7891958.20        19178  4.53   4.50  86836.40          19178 22.64  21.70 434150.10
9                   2396   69.33   50.00  166111.00     2396 706.92 656.10 1693790.30         2396 29.90  29.50  71650.60           2396 27.84  23.90  66713.70
10                 12397   50.78   40.00  629577.00    12397 289.66 288.90 3590870.50        12397 26.45  26.40 327951.70          12397  6.42   4.30  79547.10
11                  6201   62.50   45.00  387569.00     6201 611.63 596.10 3792721.80         6201 11.97  11.70  74207.60           6201 31.42  30.90 194848.80
12                 10043   53.90   40.00  541310.00    10043 367.81 362.10 3693891.00        10043 13.22  13.10 132773.10          10043 17.33  14.50 174072.40
13                  4568  535.93  495.00 2448145.00     4568 314.96 316.10 1438739.20         4568  3.41   3.40  15555.80           4568 23.65  22.60 108054.90
14                 22182   40.08   30.00  889101.00    22182 123.45 119.60 2738441.80        22182  6.80   6.80 150825.80          22182  4.13   2.50  91638.50
15                   443 1572.56 1470.00  696645.50      443 352.06 281.70  155962.40          443 29.67  29.10  13142.90            443 10.22   4.40   4527.40
16                 15612   47.01   35.00  733968.00    15612 208.96 208.60 3262332.00        15612 17.70  17.60 276313.20          15612  5.02   3.40  78373.10
17                  1485   77.71   45.00  115396.00     1485 959.80 905.80 1425308.70         1485 16.71  16.60  24809.10           1485 39.17  38.10  58171.30
18                  3009  448.00  435.00 1348044.00     3009 344.02 338.10 1035156.30         3009 11.16  10.70  33581.80           3009 22.19  21.80  66765.10
19                 26725   45.50   35.00 1215865.00    26725 351.77 345.40 9401114.50        26725  1.57   1.60  41872.10          26725 21.09  19.40 563634.20
20                  4374   60.03   40.00  262578.00     4374 869.93 827.95 3805052.90         4374  5.08   5.10  22200.00           4374 39.05  37.00 170820.30
21                  9692   54.90   45.00  532060.00     9692 302.47 306.90 2931505.10         9692 31.66  31.60 306825.00           9692  5.49   4.20  53177.00
22                 17917   55.96   45.00 1002547.00    17917 337.36 332.80 6044557.30        17917  8.23   8.10 147435.40          17917 17.84  16.10 319677.20
23                 25868   35.17   28.00  909754.00    25868  97.79  98.80 2529551.20        25868  3.58   3.50  92496.90          25868  3.72   2.60  96137.70
24                  1930 1601.28 1500.00 3090469.50     1930 225.10 172.85  434449.00         1930  2.66   2.05   5138.90           1930 11.88   5.10  22936.00
25                 13010   54.06   40.00  703364.00    13010 562.92 547.90 7323591.70        13010  2.24   2.30  29159.40          13010 31.58  30.50 410806.30
26                  5825   58.87   45.00  342917.00     5825 499.27 483.10 2908228.50         5825 19.68  19.50 114640.00           5825 22.41  19.80 130526.30
27                 18343   42.58   30.00  780961.00    18343 148.99 145.80 2732977.40        18343 10.11  10.10 185395.40          18343  4.42   2.80  81092.80
28                  6536  267.95  255.00 1751322.00     6536 178.33 173.40 1165553.80         6536  2.82   2.60  18429.90           6536 10.98   6.50  71765.80
29                  1416  478.20  480.00  677130.00     1416 323.01 304.65  457384.20         1416 24.21  23.90  34280.90           1416 14.82   7.10  20978.40
30                 35090   29.79   20.00 1045430.00    35090  61.04  61.60 2141793.80        35090  0.68   0.50  23706.10          35090  2.61   1.60  91517.00